
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.File;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aya
 */
public class About extends javax.swing.JFrame {

    static Clip clipAbout;
    AudioInputStream audio;
    /**
     * Creates new form HowToPlay
     */
    public About() {
        mainPage.clipMain.close();
        initComponents();
        
        try{
            String soundB = "The Angry Birds Movie- Hatchlings Seasons Greetings (online-audio-converter.com) (mp3cut.net).wav";
            audio = AudioSystem.getAudioInputStream(new File(soundB).getAbsoluteFile());
            clipAbout = AudioSystem.getClip();
            clipAbout.open(audio);
            clipAbout.start();
            clipAbout.loop(1000);
        }catch(Exception e){
            System.err.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        OKAY = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setLayout(null);

        OKAY.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        OKAY.setText("OKAY !");
        OKAY.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OKAY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKAYActionPerformed(evt);
            }
        });
        jPanel1.add(OKAY);
        OKAY.setBounds(520, 400, 130, 50);

        jLabel11.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        jLabel11.setText("Pleace help the poor birds to achieve their mission!");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 620, 690, 30);

        jLabel10.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        jLabel10.setText("But they are too young and small to do it alone. So they asked for your help!");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 590, 690, 30);

        jLabel9.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        jLabel9.setText(" The young birds decided to help their mummies by collecting their brothers' eggs.");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 560, 710, 30);

        jLabel8.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        jLabel8.setText(" to put it in a safe place.");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 530, 680, 30);

        jLabel7.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        jLabel7.setText("The birds spies knew about that and warned them, so they decided to collect all the eggs,");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 500, 690, 30);

        jLabel6.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        jLabel6.setText("The pigs decided to attack the birds village to steal their eggs to celebrate by eating it.");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 460, 680, 40);

        jLabel5.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        jLabel5.setText("On the occasion of the anniversary of the new year,");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 430, 660, 30);

        jLabel4.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        jLabel4.setText("Happy New Year!");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 390, 660, 50);

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ABOUT THE GAME");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 700, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aboutgif105.gif"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 60, 600, 340);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/Snow-White-Polished-Porcelain-Tile-600x600-with.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 700, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void OKAYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKAYActionPerformed
        // TODO add your handling code here:
        
        new mainPage().setVisible(true);
        close();
        clipAbout.close();
    }//GEN-LAST:event_OKAYActionPerformed
    public void close(){
        WindowEvent win=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(win);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new About().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OKAY;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
