
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.File;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aya
 */
public class HowToPlay extends javax.swing.JFrame {
    static Clip clipHow;
    static AudioInputStream audio;
    /**
     * Creates new form HowToPlay
     */
    public HowToPlay() {
        initComponents();
        mainPage.clipMain.close();
         try{
            String soundB = "BackGroundSound.wav";
            audio = AudioSystem.getAudioInputStream(new File(soundB).getAbsoluteFile());
            clipHow = AudioSystem.getClip();
            clipHow.open(audio);
            clipHow.start();
            clipHow.loop(1000);
        }catch(Exception e){
            System.err.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        GOTIT = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 700));
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/escape-button-key.png"))); // NOI18N
        jPanel1.add(jLabel22);
        jLabel22.setBounds(430, 560, 40, 30);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/space.png"))); // NOI18N
        jPanel1.add(jLabel21);
        jLabel21.setBounds(510, 520, 40, 30);

        jLabel20.setFont(new java.awt.Font("Poor Richard", 1, 24)); // NOI18N
        jLabel20.setText("to exit the game.");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(480, 560, 180, 30);

        jLabel19.setFont(new java.awt.Font("Poor Richard", 1, 24)); // NOI18N
        jLabel19.setText("to pause.");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(570, 520, 100, 30);

        jLabel18.setFont(new java.awt.Font("Poor Richard", 1, 24)); // NOI18N
        jLabel18.setText("And");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(370, 554, 50, 40);

        jLabel17.setFont(new java.awt.Font("Poor Richard", 1, 24)); // NOI18N
        jLabel17.setText("You can use");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(370, 510, 120, 40);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goldEgg.png"))); // NOI18N
        jPanel1.add(jLabel16);
        jLabel16.setBounds(620, 430, 40, 30);

        jLabel15.setFont(new java.awt.Font("Poor Richard", 1, 24)); // NOI18N
        jLabel15.setText("It will make you gain a life.");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(370, 464, 320, 40);

        jLabel14.setFont(new java.awt.Font("Poor Richard", 1, 24)); // NOI18N
        jLabel14.setText("Don't miss the gold one,");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(370, 420, 320, 40);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackEgg.png"))); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(630, 330, 40, 30);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/whiteEgg.png"))); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(630, 270, 40, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nestxxx130x70.png"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(560, 180, 130, 70);

        GOTIT.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        GOTIT.setText("GOT IT !");
        GOTIT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GOTIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GOTITActionPerformed(evt);
            }
        });
        jPanel1.add(GOTIT);
        GOTIT.setBounds(490, 600, 160, 50);

        jLabel11.setFont(new java.awt.Font("Poor Richard", 1, 24)); // NOI18N
        jLabel11.setText("or you will lose a life.");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(370, 370, 300, 40);

        jLabel10.setFont(new java.awt.Font("Poor Richard", 1, 24)); // NOI18N
        jLabel10.setText("Don't catch the black one,");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(370, 320, 330, 40);

        jLabel9.setFont(new java.awt.Font("Poor Richard", 1, 24)); // NOI18N
        jLabel9.setText("to collect the white eggs");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(380, 260, 280, 50);

        jLabel7.setFont(new java.awt.Font("Poor Richard", 1, 24)); // NOI18N
        jLabel7.setText("Move the mouse, ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(384, 204, 300, 40);

        jLabel6.setFont(new java.awt.Font("Poor Richard", 1, 24)); // NOI18N
        jLabel6.setText("As you accepted to help us.");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(380, 160, 310, 40);

        jLabel5.setFont(new java.awt.Font("Poor Richard", 1, 24)); // NOI18N
        jLabel5.setText("Mummies are grateful,");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(380, 120, 290, 40);

        jLabel4.setFont(new java.awt.Font("Poor Richard", 1, 24)); // NOI18N
        jLabel4.setText("Welcome Mighty..");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(380, 80, 310, 40);

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("HOW TO PLAY");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(4, 4, 690, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SSSSSsetset2376x668.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 80, 376, 620);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/Snow-White-Polished-Porcelain-Tile-600x600-with.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void GOTITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GOTITActionPerformed
        // TODO add your handling code here:
        
        new mainPage().setVisible(true);
        clipHow.close();
        close();
    }//GEN-LAST:event_GOTITActionPerformed
public void close(){
        WindowEvent win=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(win);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HowToPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HowToPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HowToPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HowToPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HowToPlay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GOTIT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
