
//import static AnimGLEventListener3.cnt;
import static com.sun.xml.internal.ws.streaming.XMLStreamReaderUtil.close;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author top10
 */
public class levels extends javax.swing.JFrame {
    
    static Anim b;
    /**
     * Creates new form levels
     */
    public levels() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MEDUIM = new javax.swing.JButton();
        HARD = new javax.swing.JButton();
        EASY = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        MEDUIM.setFont(new java.awt.Font("Showcard Gothic", 1, 36)); // NOI18N
        MEDUIM.setText("MEDUIM");
        MEDUIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MEDUIMActionPerformed(evt);
            }
        });
        jPanel1.add(MEDUIM);
        MEDUIM.setBounds(250, 490, 190, 80);

        HARD.setFont(new java.awt.Font("Showcard Gothic", 1, 36)); // NOI18N
        HARD.setText("HARD");
        HARD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HARDActionPerformed(evt);
            }
        });
        jPanel1.add(HARD);
        HARD.setBounds(480, 490, 190, 80);

        EASY.setFont(new java.awt.Font("Showcard Gothic", 1, 36)); // NOI18N
        EASY.setText("EASY");
        EASY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EASYActionPerformed(evt);
            }
        });
        jPanel1.add(EASY);
        EASY.setBounds(20, 490, 190, 80);

        jLabel5.setFont(new java.awt.Font("Showcard Gothic", 1, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("PICK A LEVEL MIGHTY!");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(24, 10, 660, 130);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mighty/medAc.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(180, 120, 270, 360);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mighty/hardAC.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(430, 160, 280, 290);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mighty/easy_197x296.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 150, 200, 290);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WhiteBackGround_700x700.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void close(){
        WindowEvent win=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(win);
    }
    private void EASYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EASYActionPerformed
        //new Anim().setVisible(true);
        b = new Anim();
        b.setVisible(true);
        AnimGLEventListener3.cnt = 0;
        AnimGLEventListener3.life = 5 ;
        AnimGLEventListener3.score = 0;
        AnimGLEventListener3.sec = 0;
        AnimGLEventListener3.min = 0;
        AnimGLEventListener3.mod = 250;
        AnimGLEventListener3.dy = 1;
        AnimGLEventListener3.whiteRatio = 0.8;
        AnimGLEventListener3.blackRatio = 0.9;
        AnimGLEventListener3.eggRate = 7;
        AnimGLEventListener3.level = "easy";
       // b. setVisible(true);
        //mainPage.pa.setVisible(false);
        close();
    }//GEN-LAST:event_EASYActionPerformed

    private void MEDUIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MEDUIMActionPerformed
        
        //new Anim().setVisible(true);
        b = new Anim();
        b.setVisible(true);
        AnimGLEventListener3.cnt = 0;
        AnimGLEventListener3.life = 5 ;
        AnimGLEventListener3.score = 0;
        AnimGLEventListener3.sec = 0;
        AnimGLEventListener3.min = 0;
        AnimGLEventListener3.mod = 500;
        AnimGLEventListener3.dy = 1.5;
        AnimGLEventListener3.whiteRatio = 0.75;
        AnimGLEventListener3.blackRatio = 0.95;
        AnimGLEventListener3.eggRate = 6;
        AnimGLEventListener3.level = "meduim";
        //b. setVisible(true);
        //mainPage.pa.setVisible(false);
        close();
    }//GEN-LAST:event_MEDUIMActionPerformed

    private void HARDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HARDActionPerformed
        b = new Anim();
        b.setVisible(true);
        AnimGLEventListener3.cnt = 0;
        AnimGLEventListener3.life = 5 ;
        AnimGLEventListener3.score = 0;
        AnimGLEventListener3.sec = 0;
        AnimGLEventListener3.min = 0;
        AnimGLEventListener3.mod = 250;
        AnimGLEventListener3.dy = 2;
        AnimGLEventListener3.whiteRatio = 0.7;
        AnimGLEventListener3.blackRatio = 0.98;
        AnimGLEventListener3.eggRate = 5;
        AnimGLEventListener3.level = "hard";
        //new Anim().setVisible(true);
       // b. setVisible(true);
        
        //mainPage.pa.setVisible(false);
        close();
    }//GEN-LAST:event_HARDActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(levels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(levels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(levels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(levels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new levels().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EASY;
    private javax.swing.JButton HARD;
    private javax.swing.JButton MEDUIM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
