
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.File;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aya
 */
public class mainPage extends javax.swing.JFrame {
    static Clip clipMain;
    static AudioInputStream audio;
    static Anim a = new Anim();
    static levels pa;
    /**
     * Creates new form mainPage
     */
    public mainPage() {
        initComponents();
        start.clipStart.close();
         try{
            String soundB = "BackGroundSound.wav";
            audio = AudioSystem.getAudioInputStream(new File(soundB).getAbsoluteFile());
            clipMain = AudioSystem.getClip();
            clipMain.open(audio);
            clipMain.start();
            clipMain.loop(1000);
        }catch(Exception e){
            System.err.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        EXIT = new javax.swing.JButton();
        PLAY = new javax.swing.JButton();
        ABOUT = new javax.swing.JButton();
        HOWTOPLAY = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setMaximumSize(new java.awt.Dimension(700, 700));
        setMinimumSize(new java.awt.Dimension(700, 700));
        setPreferredSize(new java.awt.Dimension(700, 700));
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        jPanel1.setLayout(null);

        EXIT.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        EXIT.setText("EXIT");
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });
        jPanel1.add(EXIT);
        EXIT.setBounds(220, 490, 220, 50);

        PLAY.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        PLAY.setText("PLAY");
        PLAY.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PLAY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PLAYActionPerformed(evt);
            }
        });
        jPanel1.add(PLAY);
        PLAY.setBounds(220, 180, 220, 50);

        ABOUT.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        ABOUT.setText("ABOUT");
        ABOUT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ABOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABOUTActionPerformed(evt);
            }
        });
        jPanel1.add(ABOUT);
        ABOUT.setBounds(220, 290, 220, 50);

        HOWTOPLAY.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        HOWTOPLAY.setText("HOW TO PLAY");
        HOWTOPLAY.setActionCommand("HOWTOPLAY");
        HOWTOPLAY.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HOWTOPLAY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HOWTOPLAYActionPerformed(evt);
            }
        });
        jPanel1.add(HOWTOPLAY);
        HOWTOPLAY.setBounds(220, 390, 220, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newMain.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-6, 0, 700, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("main");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ABOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABOUTActionPerformed
        // TODO add your handling code here:
        
        new About().setVisible(true);
        close();
    }//GEN-LAST:event_ABOUTActionPerformed
public void close(){
        WindowEvent win=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(win);
    }
    private void HOWTOPLAYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HOWTOPLAYActionPerformed
        // TODO add your handling code here:
        
        new HowToPlay().setVisible(true);
        close();
    }//GEN-LAST:event_HOWTOPLAYActionPerformed

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
        // TODO add your handling code here:
        
        new EXIT().setVisible(true);
        close();
    }//GEN-LAST:event_EXITActionPerformed

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyCode() == evt.VK_7)
            new Esc().setVisible(true);
    }//GEN-LAST:event_formKeyTyped

    private void PLAYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PLAYActionPerformed
        // TODO add your handling code here:
       //a. setVisible(true);
       
       pa = new levels();
       pa.setVisible(true);
        close();
       
    }//GEN-LAST:event_PLAYActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new mainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ABOUT;
    private javax.swing.JButton EXIT;
    private javax.swing.JButton HOWTOPLAY;
    private javax.swing.JButton PLAY;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
